---

rootGroup: root

sysctl_params:
  - name: net.netfilter.nf_conntrack_max
    value: 65536
  - name: net.ipv4.tcp_max_syn_backlog
    value: 8192
  - name: net.core.somaxconn
    value: 65535
  - name: net.core.netdev_max_backlog
    value: 16384
  - name: net.ipv4.tcp_mem
    value: 45147 60198 90294
  - name: net.ipv4.tcp_max_tw_buckets
    value: 16384
  - name: net.ipv4.tcp_max_orphans
    value: 16384
